#!/bin/bash
#
# ZNC Installer
#
# Originally written for QuickBox.io by liara
#
# QuickBox Copyright (C) 2017 QuickBox.io
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.

user=$(cut -d: -f1 < /root/.master.info)
passwd=$(cut -d: -f2 < /root/.master.info)
salt=$( head /dev/urandom | tr -dc A-Za-z0-9 | head -c 20; echo "")
shapass=$(echo -n $passwd$salt | sha256sum | awk '{print $1}')
port=$(cat /home/seedit4me/.znc_port)
DISTRO=$(lsb_release -is)
CODENAME=$(lsb_release -cs)
#shellcheck source=sources/functions/letsencrypt
. /etc/swizzin/sources/functions/letsencrypt

echo_progress_start "Creating system user for znc"
useradd znc -m -s /bin/bash
passwd znc -l >> ${log} 2>&1
echo_progress_done

if [[ $DISTRO == Debian ]]; then
    #shellcheck source=sources/functions/backports
    . /etc/swizzin/sources/functions/backports
    check_debian_backports
    set_packages_to_backports znc
    apt_update
elif [[ $CODENAME == "bionic" ]]; then
    add-apt-repository --yes ppa:teward/znc >> ${log} 2>&1
    apt_update
fi
apt_install znc

echo_progress_start "Installing systemd service"
cat > /etc/systemd/system/znc.service << ZNC
[Unit]
Description=ZNC, an advanced IRC bouncer
After=network-online.target
     
[Service]
ExecStart=/usr/bin/znc -f
User=znc
Restart=always
     
[Install]
WantedBy=multi-user.target
ZNC

sudo -u znc mkdir -p /home/znc/.znc
sudo -u znc mkdir /home/znc/.znc/configs
chmod 700 /home/znc
sudo -u znc znc --makepem

cat > /home/znc/.znc/configs/znc.conf << ZNCONF
// WARNING
//
// Do NOT edit this file while ZNC is running!
// Use webadmin or *controlpanel instead.
//
// Altering this file by hand will forfeit all support.
//
// But if you feel risky, you might want to read help on /znc saveconfig and /znc rehash.
// Also check http://en.znc.in/wiki/Configuration

Version = 1.9.0
<Listener l>
    Port = 28404
    IPv4 = true
    IPv6 = false
    SSL  = true
    AllowIRC = true
    AllowWeb = true
</Listener>

LoadModule = webadmin

<User seedit4me>
		<Pass password>
		        Method = sha256
		        Hash = ${shapass}
		        Salt = ${salt}
		</Pass>
//        Pass       = sha256#${shapass}#${salt}#
        Admin      = ${user}
        Nick       = ${user}
        AltNick    = ${user}_
        Ident      = ${user}
        RealName   = Got ZNC?
        LoadModule = chansaver
        LoadModule = controlpanel
</User>
ZNCONF

chown -R znc:znc /home/znc/.znc/configs
chmod -R 777 /home/znc/.znc/configs

systemctl enable -q znc
echo_progress_done

sleep 5
killall -u znc znc > /dev/null 2>&1
sleep 1

# Check for LE cert, and copy it into znc.pem so ZNC can offer SSL on its IRC port.
if [[ -f /install/nginx.lock ]]; then
    le_znc_hook
fi

systemctl start znc

# Install nginx reverse proxy config for ZNC web admin UI
if [[ -f /install/.nginx.lock ]]; then
    echo_progress_start "Installing nginx config for znc"
    bash /etc/swizzin/scripts/nginx/znc.sh
    systemctl reload nginx >> $log 2>&1
    echo_progress_done "Nginx config for znc installed"
fi

echo "$(grep Port /home/znc/.znc/configs/znc.conf | sed -e 's/^[ \t]*//')" > /install/.znc.lock
echo "$(grep SSL /home/znc/.znc/configs/znc.conf | sed -e 's/^[ \t]*//')" >> /install/.znc.lock
echo_success "ZNC installed"
